modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="tciu_compat"
version="1.0.0"
displayName="Tinkers Construct + Industrial Upgrade Compat"
description='''Compatibility patch for TConstruct and Industrial Upgrade.'''

[[dependencies.tciu_compat]]
modId="tconstruct"
mandatory=true
versionRange="[5.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tciu_compat]]
modId="industrialupgrade"
mandatory=true
versionRange="[3.3.0,)" # adjust as needed
ordering="AFTER"
side="BOTH"
